#pragma once

#include <raylib.h>

typedef enum {
    THEME_CATPUCCIN_LATTE,
    THEME_CATPUCCIN_FRAPPE,
    THEME_CATPUCCIN_MACCHIATO,
    THEME_CATPUCCIN_MOCHA,
    THEME_COUNT
} Theme;

typedef enum {
    COLOR_ROSEWATER,
    COLOR_FLAMINGO,
    COLOR_PINK,
    COLOR_MAUVE,
    COLOR_RED,
    COLOR_MAROON,
    COLOR_PEACH,
    COLOR_YELLOW,
    COLOR_GREEN,
    COLOR_TEAL,
    COLOR_SKY,
    COLOR_SAPPHIRE,
    COLOR_BLUE,
    COLOR_LAVENDER,
    COLOR_TEXT,
    COLOR_SUBTEXT1,
    COLOR_SUBTEXT0,
    COLOR_OVERLAY2,
    COLOR_OVERLAY1,
    COLOR_OVERLAY0,
    COLOR_SURFACE2,
    COLOR_SURFACE1,
    COLOR_SURFACE0,
    COLOR_BASE,
    COLOR_MANTLE,
    COLOR_CRUST,
    COLOR_COUNT,
} Color_Name;

extern int g_color[THEME_COUNT][COLOR_COUNT];
extern Color g_rcolor[THEME_COUNT][COLOR_COUNT];
void color_init(void);
